{
 "title": "NSP-Thresholds-1h",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Anomaly Detections 1h",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(anomaly_detected_count_total[1h])"
    }
   ]
  },
  {
   "title": "Anomaly Detections 24h",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(anomaly_detected_count_total[24h])"
    }
   ]
  },
  {
   "title": "Anomaly Detections 7d",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(anomaly_detected_count_total[7d])"
    }
   ]
  },
  {
   "title": "Threshold Violations 1h",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(threshold_violation_count_total[1h]))"
    }
   ]
  },
  {
   "title": "Threshold Violations 24h",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(threshold_violation_count_total[24h]))"
    }
   ]
  },
  {
   "title": "Threshold Violations 7d",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(threshold_violation_count_total[7d]))"
    }
   ]
  }
 ]
}